# Generated by Django 5.1.6 on 2025-02-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygene', '0002_patient_is_pending_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
